use super::types::{TemplateBone, TemplatePoint};

pub(super) static BIPED_POINTS: &[TemplatePoint] = &[
    TemplatePoint {
        name: "head_top",
        kind: "anchor",
        nx: 0.5,
        ny: 0.04,
    },
    TemplatePoint {
        name: "neck",
        kind: "joint",
        nx: 0.5,
        ny: 0.18,
    },
    TemplatePoint {
        name: "shoulder_l",
        kind: "joint",
        nx: 0.36,
        ny: 0.23,
    },
    TemplatePoint {
        name: "shoulder_r",
        kind: "joint",
        nx: 0.64,
        ny: 0.23,
    },
    TemplatePoint {
        name: "elbow_l",
        kind: "joint",
        nx: 0.31,
        ny: 0.38,
    },
    TemplatePoint {
        name: "elbow_r",
        kind: "joint",
        nx: 0.69,
        ny: 0.38,
    },
    TemplatePoint {
        name: "hand_l",
        kind: "anchor",
        nx: 0.29,
        ny: 0.52,
    },
    TemplatePoint {
        name: "hand_r",
        kind: "anchor",
        nx: 0.71,
        ny: 0.52,
    },
    TemplatePoint {
        name: "hip",
        kind: "joint",
        nx: 0.5,
        ny: 0.52,
    },
    TemplatePoint {
        name: "hip_l",
        kind: "joint",
        nx: 0.43,
        ny: 0.54,
    },
    TemplatePoint {
        name: "hip_r",
        kind: "joint",
        nx: 0.57,
        ny: 0.54,
    },
    TemplatePoint {
        name: "knee_l",
        kind: "joint",
        nx: 0.44,
        ny: 0.72,
    },
    TemplatePoint {
        name: "knee_r",
        kind: "joint",
        nx: 0.56,
        ny: 0.72,
    },
    TemplatePoint {
        name: "foot_l",
        kind: "contact",
        nx: 0.42,
        ny: 0.95,
    },
    TemplatePoint {
        name: "foot_r",
        kind: "contact",
        nx: 0.58,
        ny: 0.95,
    },
];

pub(super) static BIPED_BONES: &[TemplateBone] = &[
    TemplateBone {
        name: "torso",
        start: "neck",
        end: "hip",
        radius_factor: 1.4,
        parent: None,
        z: 5,
    },
    TemplateBone {
        name: "head",
        start: "neck",
        end: "head_top",
        radius_factor: 1.2,
        parent: Some("torso"),
        z: 7,
    },
    TemplateBone {
        name: "upper_arm_l",
        start: "shoulder_l",
        end: "elbow_l",
        radius_factor: 0.7,
        parent: Some("torso"),
        z: 2,
    },
    TemplateBone {
        name: "lower_arm_l",
        start: "elbow_l",
        end: "hand_l",
        radius_factor: 0.6,
        parent: Some("upper_arm_l"),
        z: 2,
    },
    TemplateBone {
        name: "upper_arm_r",
        start: "shoulder_r",
        end: "elbow_r",
        radius_factor: 0.7,
        parent: Some("torso"),
        z: 9,
    },
    TemplateBone {
        name: "lower_arm_r",
        start: "elbow_r",
        end: "hand_r",
        radius_factor: 0.6,
        parent: Some("upper_arm_r"),
        z: 9,
    },
    TemplateBone {
        name: "thigh_l",
        start: "hip_l",
        end: "knee_l",
        radius_factor: 0.8,
        parent: Some("torso"),
        z: 2,
    },
    TemplateBone {
        name: "shin_l",
        start: "knee_l",
        end: "foot_l",
        radius_factor: 0.6,
        parent: Some("thigh_l"),
        z: 2,
    },
    TemplateBone {
        name: "thigh_r",
        start: "hip_r",
        end: "knee_r",
        radius_factor: 0.8,
        parent: Some("torso"),
        z: 9,
    },
    TemplateBone {
        name: "shin_r",
        start: "knee_r",
        end: "foot_r",
        radius_factor: 0.6,
        parent: Some("thigh_r"),
        z: 9,
    },
];
